sudo: required

services:
  - docker

install:
  - docker build -t 20uf/jenkins-ci-php-synology .
  - docker run -d -p 127.0.0.1:8080:8080 --name 20uf/jenkins-ci-php-synology 20uf/jenkins-ci-php-synology

script:
  - docker ps | grep -q 20uf/jenkins-ci-php-synology
